version: '3'
services:

  db:
    restart: always
    image: postgres:alpine
#    volumes:
#      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
#    volumes:
#      - ./redis:/data

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    ports:
      - "9200:9200"
#    volumes:
#      - ./redis:/data

  memcached:
    restart: always
    image: memcached:alpine
#    volumes:
#      - ./redis:/data

  web:
    build: .
    image: feedbin/feedbin
    restart: always
    env_file: .env.development
    command: rackup --bind=0.0.0.0:9292
    ports:
      - "9292:9292"
    volumes:
      - ./public:/feedbin/public
    depends_on:
      - db
      - redis
      - elasticsearch
      - memcached

  worker:
    build: .
    image: feedbin/feedbin
    restart: always
    env_file: .env.development
    command: bundle exec foreman start
    depends_on:
      - db
      - redis
      - elasticsearch
      - memcached
